package p115account

import "errors"

var (
	ErrStoreUnavailable                 = errors.New("p115 account store unavailable")
	ErrValidatorUnavailable             = errors.New("p115 credential validator unavailable")
	ErrAccountNotFound                  = errors.New("115 账号不存在")
	ErrAccountIDRequired                = errors.New("115 账号 ID 不能为空")
	ErrAccountUnavailable               = errors.New("115 账号尚未验证为有效状态")
	ErrAccountCoolingDown               = errors.New("115 账号处于运行期冷却")
	ErrCredentialChanged                = errors.New("Cookie 已被替换，请重新验证")
	ErrRuntimeStateChanged              = errors.New("115 账号运行期状态已变化")
	ErrRuntimeHealthOutcomeInvalid      = errors.New("115 账号运行期健康结果无效")
	ErrRoleAlreadyEnabled               = errors.New("该角色已有启用的 115 账号")
	ErrProviderUserAlreadyEnabled       = errors.New("源账号和播放账号不能使用同一个 115 账号")
	ErrInvalidRole                      = errors.New("115 账号角色无效")
	ErrAliasRequired                    = errors.New("115 账号别名不能为空")
	ErrAliasInvalid                     = errors.New("115 账号别名长度不能超过 100 个字符")
	ErrCookieRequired                   = errors.New("115 Cookie 不能为空")
	ErrCookieInvalid                    = errors.New("115 Cookie 格式或长度无效")
	ErrAppTypeRequired                  = errors.New("无法从 Cookie 识别客户端类型，请手动填写 appType")
	ErrAppTypeInvalid                   = errors.New("115 appType 格式或长度无效")
	ErrUserAgentRequired                = errors.New("115 User-Agent 不能为空")
	ErrUserAgentInvalid                 = errors.New("115 User-Agent 格式或长度无效")
	ErrTargetParentInvalid              = errors.New("115 目标目录 ID 长度不能超过 64 个字符")
	ErrPlaybackTargetParentRequired     = errors.New("播放账号必须设置目标目录")
	ErrSourceTargetParentUnexpected     = errors.New("源账号不能设置播放目标目录")
	ErrEmbyPathPrefixRequired           = errors.New("源账号必须设置 Emby 挂载目录")
	ErrEmbyPathPrefixInvalid            = errors.New("Emby 挂载目录格式无效")
	ErrSourceRootIDRequired             = errors.New("源账号必须设置 115 源目录 ID")
	ErrSourceRootIDInvalid              = errors.New("115 源目录 ID 格式无效")
	ErrPlaybackSourceLocationUnexpected = errors.New("播放账号不能设置源目录")
	ErrSourceLocationOnly               = errors.New("只有源账号可以配置源目录")
)
